- name: Install docker
  hosts:  [MyHosts]
  become: true
  tasks:
    - name: Install apt https transport packages
      apt: pkg=apt-transport-https update_cache=yes cache_valid_time=600

    - name: Install certificates packages
      apt: pkg=ca-certificates update_cache=yes cache_valid_time=600

    - name: Add docker GPG key
      apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

    - name: Add docker apt repository
      apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present update_cache=yes

    - name: Install docker engine
      apt: pkg=docker-engine update_cache=yes cache_valid_time=1

    - name: Run docker
      service: name=docker state=started
